curva_historica:
  CCPEDS: "16/12/2025"
  CCPSS: "16/12/2025"
  CCPVS: "16/12/2025"
  CSBCRD: "16/12/2025"
  CCCLD: "16/12/2025"
  CBCRS: "16/12/2025"
  CCSDF: "16/12/2025"
  CBCRPS: "16/12/2025"
  CCINFS: "16/12/2025"


indice_spreads_corporativos:
  CCCLD: "10/10/2025"
  CCPSS: "05/12/2025"
  CCPVS: "05/12/2025"
  CSBCRD: "05/12/2025"

vp_rentafija:
  rf: "05/12/2025"


  