curva_historica:
  CCPEDS: "15/12/2025"
  CCPSS: "15/12/2025"
  CCPVS: "15/12/2025"
  CSBCRD: "15/12/2025"
  CCCLD: "15/12/2025"
  CBCRS: "15/12/2025"
  CCSDF: "15/12/2025"
  CBCRPS: "15/12/2025"
  CCINFS: "15/12/2025"


indice_spreads_corporativos:
  CCCLD: "10/10/2025"
  CCPSS: "05/12/2025"
  CCPVS: "05/12/2025"
  CSBCRD: "05/12/2025"

vp_rentafija:
  rf: "05/12/2025"


  