curva_historica:
  CCPEDS: "23/12/2025"
  CCPSS: "23/12/2025"
  CCPVS: "23/12/2025"
  CSBCRD: "23/12/2025"
  CCCLD: "23/12/2025"
  CBCRS: "23/12/2025"
  CCSDF: "23/12/2025"
  CBCRPS: "23/12/2025"
  CCINFS: "23/12/2025"


indice_spreads_corporativos:
  CCCLD: "10/10/2025"
  CCPSS: "05/12/2025"
  CCPVS: "05/12/2025"
  CSBCRD: "05/12/2025"

vp_rentafija:
  rf: "05/12/2025"


  