curva_historica:
  CCPEDS: "22/12/2025"
  CCPSS: "22/12/2025"
  CCPVS: "22/12/2025"
  CSBCRD: "22/12/2025"
  CCCLD: "22/12/2025"
  CBCRS: "22/12/2025"
  CCSDF: "22/12/2025"
  CBCRPS: "22/12/2025"
  CCINFS: "22/12/2025"


indice_spreads_corporativos:
  CCCLD: "10/10/2025"
  CCPSS: "05/12/2025"
  CCPVS: "05/12/2025"
  CSBCRD: "05/12/2025"

vp_rentafija:
  rf: "05/12/2025"


  